In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
traffic= pd.read_csv("/Users/asadtariq/Downloads/NJRat Traffic/Traffic.csv")
traffic

,Unnamed: 0,id,expiration_id,src_ip,src_mac,src_oui,src_port,dst_ip,dst_mac,dst_oui,...,application_name,application_category_name,application_is_guessed,application_confidence,requested_server_name,client_fingerprint,server_fingerprint,user_agent,content_type,label
0,0,0,0,13.107.6.158,00:50:56:fa:cc:4c,00:50:56,443,192.168.20.145,00:0c:29:0f:cf:f6,00:0c:29,...,TLS,Web,1,1,NaN,NaN,NaN,NaN,NaN,0
1,1,1,0,204.79.197.222,00:50:56:fa:cc:4c,00:50:56,443,192.168.20.145,00:0c:29:0f:cf:f6,00:0c:29,...,TLS,Web,1,1,NaN,NaN,NaN,NaN,NaN,0
2,2,2,0,192.168.20.145,00:0c:29:0f:cf:f6,00:0c:29,49722,94.97.232.235,00:50:56:fa:cc:4c,00:50:56,...,TLS,Web,1,1,NaN,NaN,NaN,NaN,NaN,0
3,3,3,0,192.168.20.145,00:0c:29:0f:cf:f6,00:0c:29,61613,192.168.20.2,00:50:56:fa:cc:4c,00:50:56,...,DNS.Microsoft,Network,0,6,nav.smartscreen.microsoft.com,NaN,NaN,NaN,NaN,0
4,4,4,0,192.168.20.145,00:0c:29:0f:cf:f6,00:0c:29,49723,20.82.250.189,00:50:56:fa:cc:4c,00:50:56,...,TLS.Microsoft,Cloud,0,6,nav.smartscreen.microsoft.com,ce5f3254611a8c095a3d821d44539877,986571066668055ae9481cb84fda634a,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10617,10617,470,0,fe80::f9d6:c9e4:10c0:87ed,00:0c:29:1d:15:6c,00:0c:29,0,ff02::16,33:33:00:00:00:16,33:33:00,...,ICMPV6,Network,0,6,NaN,NaN,NaN,NaN,NaN,1
10618,10618,471,0,192.168.126.142,00:0c:29:1d:15:6c,00:0c:29,58446,192.168.126.139,00:0c:29:38:db:a9,00:0c:29,...,HTTP,Web,0,6,192.168.126.139,NaN,NaN,Go-http-client/1.1,NaN,1
10619,10619,472,0,192.168.126.1,16:7d:da:ad:d3:65,16:7d:da,5353,224.0.0.251,01:00:5e:00:00:fb,01:00:5e,...,MDNS,Network,0,6,_rdlink._tcp.local,NaN,NaN,NaN,NaN,1
10620,10620,473,0,fe80::147d:daff:fead:d365,16:7d:da:ad:d3:65,16:7d:da,5353,ff02::fb,33:33:00:00:00:fb,33:33:00,...,MDNS,Network,0,6,_rdlink._tcp.local,NaN,NaN,NaN,NaN,1
10621,10621,474,0,192.168.126.2,00:50:56:ff:cd:57,00:50:56,5353,224.0.0.251,01:00:5e:00:00:fb,01:00:5e,...,MDNS,Network,0,6,_rdlink._tcp.local,NaN,NaN,NaN,NaN,1

In [14]:
df = pd.read_json('pwnjutsu_dataset-system-json-n11.json', lines=True)
print(df)

                                                     raw   sourcetype  \
0      node=n11-vm3 type=PROCTITLE msg=audit(16206490...  linux_audit
1      node=n11-vm3 type=SYSCALL msg=audit(1620649063...  linux_audit
2      node=n11-vm3 type=PROCTITLE msg=audit(16206490...  linux_audit
3      node=n11-vm3 type=SYSCALL msg=audit(1620649063...  linux_audit
4      node=n11-vm3 type=PROCTITLE msg=audit(16206490...  linux_audit
...                                                  ...          ...
99195  node=n11-vm1 type=PATH msg=audit(1620589044.25...  linux_audit
99196  node=n11-vm1 type=PATH msg=audit(1620588985.96...  linux_audit
99197  node=n11-vm1 type=PATH msg=audit(1620588852.98...  linux_audit
99198  node=n11-vm1 type=PATH msg=audit(1620588833.18...  linux_audit
99199  node=n11-vm1 type=PATH msg=audit(1620588815.92...  linux_audit

                         source                         time     host
0      /var/log/audit/audit.log  2021-05-10 12:17:43.784 UTC  n11-vm3
1      /var/log/audit/audit.log  2021-05-10 12:17:43.784 UTC  n11-vm3
2      /var/log/audit/audit.log  2021-05-10 12:17:43.784 UTC  n11-vm3
3      /var/log/audit/audit.log  2021-05-10 12:17:43.784 UTC  n11-vm3
4      /var/log/audit/audit.log  2021-05-10 12:17:43.784 UTC  n11-vm3
...                         ...                          ...      ...
99195  /var/log/audit/audit.log  2021-05-09 00:10:00.000 UTC  n11-vm1
99196  /var/log/audit/audit.log  2021-05-09 00:10:00.000 UTC  n11-vm1
99197  /var/log/audit/audit.log  2021-05-09 00:10:00.000 UTC  n11-vm1
99198  /var/log/audit/audit.log  2021-05-09 00:10:00.000 UTC  n11-vm1
99199  /var/log/audit/audit.log  2021-05-09 00:10:00.000 UTC  n11-vm1

[99200 rows x 5 columns]

In [21]:
df

,raw,sourcetype,source,time,host
0,node=n11-vm3 type=PROCTITLE msg=audit(16206490...,linux_audit,/var/log/audit/audit.log,2021-05-10 12:17:43.784 UTC,n11-vm3
1,node=n11-vm3 type=SYSCALL msg=audit(1620649063...,linux_audit,/var/log/audit/audit.log,2021-05-10 12:17:43.784 UTC,n11-vm3
2,node=n11-vm3 type=PROCTITLE msg=audit(16206490...,linux_audit,/var/log/audit/audit.log,2021-05-10 12:17:43.784 UTC,n11-vm3
3,node=n11-vm3 type=SYSCALL msg=audit(1620649063...,linux_audit,/var/log/audit/audit.log,2021-05-10 12:17:43.784 UTC,n11-vm3
4,node=n11-vm3 type=PROCTITLE msg=audit(16206490...,linux_audit,/var/log/audit/audit.log,2021-05-10 12:17:43.784 UTC,n11-vm3
...,...,...,...,...,...
99195,node=n11-vm1 type=PATH msg=audit(1620589044.25...,linux_audit,/var/log/audit/audit.log,2021-05-09 00:10:00.000 UTC,n11-vm1
99196,node=n11-vm1 type=PATH msg=audit(1620588985.96...,linux_audit,/var/log/audit/audit.log,2021-05-09 00:10:00.000 UTC,n11-vm1
99197,node=n11-vm1 type=PATH msg=audit(1620588852.98...,linux_audit,/var/log/audit/audit.log,2021-05-09 00:10:00.000 UTC,n11-vm1
99198,node=n11-vm1 type=PATH msg=audit(1620588833.18...,linux_audit,/var/log/audit/audit.log,2021-05-09 00:10:00.000 UTC,n11-vm1
99199,node=n11-vm1 type=PATH msg=audit(1620588815.92...,linux_audit,/var/log/audit/audit.log,2021-05-09 00:10:00.000 UTC,n11-vm1

In [20]:
df.raw[0]

'node=n11-vm3 type=PROCTITLE msg=audit(1620649063.784:20323): proctitle="/usr/local/sbin/sshd"'

In [22]:
pd.read_csv('1.log', sep=r'\\t', engine='python') #[1]

       {"ts":1620554174.622111,"uid":"CtU53Y1zrbii271iyb","id.orig_h":"10.11.1.3","id.orig_p":56356,"id.resp_h":"10.1.2.2","id.resp_p":53,"proto":"tcp","conn_state":"S0","missed_bytes":0,"history":"S","orig_pkts":1,"orig_ip_bytes":60,"resp_pkts":0,"resp_ip_bytes":0}
0       {"ts":1620554177.553751,"uid":"CDIuCT2CcQ7FJq8...
1       {"ts":1620554184.606252,"uid":"CZfCP72P8j7AoQm...
2       {"ts":1620554187.556913,"uid":"CJO4H631Id0kdme...
3       {"ts":1620554194.846408,"uid":"C0eV7r2SPH6Ac6X...
4       {"ts":1620554197.559882,"uid":"CERr1s4a9UKW4mB...
...                                                   ...
298610  {"ts":1620649063.793774,"uid":"CtHWE44RVpntf5n...
298611  {"ts":1620639357.774471,"uid":"CgcCZFtms9NlYKj...
298612  {"ts":1620586702.3198,"uid":"Cihtlw4dSNXK3JqEb...
298613  {"ts":1620554228.549907,"uid":"Cb92Rh4pWCq3PAp...
298614  {"ts":1620554177.599645,"uid":"CYpDV54QJQnGcRe...

[298615 rows x 1 columns]

In [25]:
import pandas as pd
import json

path='1.log'

log_data=open(path,'r')
result={}

In [28]:
log_data

In [38]:
import pandas as pd

df = pd.read_json('1.log', lines=True)

In [39]:
df

,ts,uid,id.orig_h,id.orig_p,id.resp_h,id.resp_p,proto,conn_state,missed_bytes,history,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,duration,orig_bytes,resp_bytes,service
0,1.620554e+09,CtU53Y1zrbii271iyb,10.11.1.3,56356,10.1.2.2,53,tcp,S0,0,S,1,60,0,0,NaN,NaN,NaN,NaN
1,1.620554e+09,CDIuCT2CcQ7FJq8aM2,10.11.1.3,56358,10.1.2.2,53,tcp,S0,0,S,3,180,0,0,3.020482,0.0,0.000000e+00,NaN
2,1.620554e+09,CZfCP72P8j7AoQmmn9,10.11.1.3,56358,10.1.2.2,53,tcp,S0,0,S,1,60,0,0,NaN,NaN,NaN,NaN
3,1.620554e+09,CJO4H631Id0kdmejEf,10.11.1.3,56360,10.1.2.2,53,tcp,S0,0,S,3,180,0,0,3.033444,0.0,0.000000e+00,NaN
4,1.620554e+09,C0eV7r2SPH6Ac6XRK8,10.11.1.3,56360,10.1.2.2,53,tcp,S0,0,S,1,60,0,0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298611,1.620649e+09,CtHWE44RVpntf5nA,10.11.1.3,46752,10.1.2.2,53,tcp,S0,0,S,3,180,0,0,3.047443,0.0,0.000000e+00,NaN
298612,1.620639e+09,CgcCZFtms9NlYKjk7,172.16.128.111,33138,10.11.1.1,22,tcp,S1,0,ShADadTTtttTTtT,649518,38042636,804025,1966198717,8960.379763,3860304.0,1.914001e+09,ssh
298613,1.620587e+09,Cihtlw4dSNXK3JqEb9,10.11.1.1,48535,172.16.1.100,9997,tcp,S1,0,ShADad,22784,29110784,15429,802479,62370.640293,27926008.0,1.630000e+02,NaN
298614,1.620554e+09,Cb92Rh4pWCq3PApZC4,10.11.1.2,49156,172.16.1.100,9997,tcp,S1,0,ShADadT,40988,57775433,40998,1640095,94844.336768,56135036.0,1.630000e+02,NaN
298615,1.620554e+09,CYpDV54QJQnGcRePN4,10.11.1.3,35150,172.16.1.100,9997,tcp,OTH,0,DaT,35423,58820102,35429,1842308,94889.477964,56977833.0,0.000000e+00,NaN

In [33]:
import glob
import pandas as pd

# create an empty list to store the dataframes
dfs = []

# use glob to get a list of all .log files in the folder
file_list = glob.glob('pwnjutsu_dataset-network-json-player_11/*.log')

# loop over each file, read it into a dataframe, and append to the list
for file in file_list:
    df = pd.read_json(file, lines=True)
    dfs.append(df)

# concatenate all dataframes in the list into a single dataframe
final_df = pd.concat(dfs, ignore_index=True)

In [36]:
df_dl = final_df[0:1000]

In [37]:
df_dl.to_csv("traffic_dl.csv")