In [1]:
# Importing Libraries
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_excel("Dummy.xlsx")
df.head()

,Index,Date,Provider,Specialty Status,Billed Amount,Sub ID,Grp ID,Pat ID,Member,Order ID,Supplier,Index2,Postal Code
0,14,2020-01,TYUTRQWSL987,Non-Specialty,0.062398,153889,153889,153889H,790847,37414,POIPOMNBTUHJ,0.736130,31236
1,15,2020-02,GHJ456789,Non-Specialty,0.089507,835640,835640,835640H,790847,27133,POIPOMNBTUHJ,0.444057,36598
2,19,2020-03,POIPOMNBTUHJ,Non-Specialty,0.197595,629553,629553,629553H,231732,20758,TYUTRQWSL987,0.893252,7354
3,13,2020-04,TYUTRQWSL987,Non-Specialty,0.228381,433189,433189,433189H,784917,46877,WRHGAS,0.238437,5972
4,32,2020-05,POIPOMNBTUHJ,Non-Specialty,0.338940,364114,364114,364114x,368313,53020,POIPOMNBTUHJ,0.173276,81528

So if Adam is a member, he sees at least 2 providers within 2 months. One provider is non specialty who charge $<1 and the second provider has to be from the provider list, who charge $>$1

I'll need Adam in this case as he fits the requirement. So, I'll need a column to show the specialty provider for Adam.


The tricky part is some members will have multiple duplicates with some meeting the criteria some are not


For example, John can see 7 providers in 1 year, with only 1 of them charge $<1 but the 6 other providers he saw are not from the list. In this case, John doesn't meet the criteria

	Provider List	Supplier
1	Neurology	ABC89
2	Pediatrics	ASD987
3	Internal Medicine	YUI2000
4	Family Medicine	TYUTRQWSL987
5	Nephrology	GHJ456789
6	Cardiology	POI456123
7	Oncology	WRHGAS
8	Endocrinology	POIPOMNBTUHJ
9	Pulmonology	POYEQWSASE4343